version: "3"
networks:
  frontend_netw:
    name: frontend_netw
    external: true
services:
  frontend_service:
    hostname: frontend
    container_name: frontend
    build:
      context: .
      target: build
    volumes:
      - ./:/app/
      - /app/node_modules/
    ports:
      - 8081:4000
    restart: always
    networks:
      - frontend_netw
      - default
    environment:
      - PORT=4000
      - WALLET_URL=api:1242/wallet
      - CATEGORIES_URL=api:1242/categories
    command: yarn dev
